/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { RigidBody } from "@react-three/rapier";

export function Sarah(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/sarah.glb");
  const { actions } = useAnimations(animations, group);
  const [mount, setMount] = React.useState(false);
  useEffect(() => {
    // const idle = Object.keys(actions).find((key) => key.includes("Idle"));
    // actions[idle].play();
    setMount(true);
  }, [actions]);
  return !mount ? null : (
    <RigidBody type="fixed" colliders="trimesh">
      <group ref={group} {...props} position={[1, -1, 0]} dispose={null}>
        <group name="Root_Scene">
          <group name="RootNode">
            <group
              name="CharacterArmature"
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <primitive object={nodes.Root} />
            </group>
            <group name="Suit_Body" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <skinnedMesh
                name="Suit_Body_1"
                geometry={nodes.Suit_Body_1.geometry}
                material={materials.Black}
                skeleton={nodes.Suit_Body_1.skeleton}
              />
              <skinnedMesh
                name="Suit_Body_2"
                geometry={nodes.Suit_Body_2.geometry}
                material={materials.White}
                skeleton={nodes.Suit_Body_2.skeleton}
              />
              <skinnedMesh
                name="Suit_Body_3"
                geometry={nodes.Suit_Body_3.geometry}
                material={materials.Skin}
                skeleton={nodes.Suit_Body_3.skeleton}
              />
            </group>
            <group name="Suit_Feet" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <skinnedMesh
                name="Suit_Feet_1"
                geometry={nodes.Suit_Feet_1.geometry}
                material={materials.Black}
                skeleton={nodes.Suit_Feet_1.skeleton}
              />
              <skinnedMesh
                name="Suit_Feet_2"
                geometry={nodes.Suit_Feet_2.geometry}
                material={materials.Skin}
                skeleton={nodes.Suit_Feet_2.skeleton}
              />
            </group>
            <group name="Suit_Head" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <skinnedMesh
                name="Suit_Head_1"
                geometry={nodes.Suit_Head_1.geometry}
                material={materials.Skin}
                skeleton={nodes.Suit_Head_1.skeleton}
              />
              <skinnedMesh
                name="Suit_Head_2"
                geometry={nodes.Suit_Head_2.geometry}
                material={materials.Hair_Blond}
                skeleton={nodes.Suit_Head_2.skeleton}
              />
              <skinnedMesh
                name="Suit_Head_3"
                geometry={nodes.Suit_Head_3.geometry}
                material={materials.Hair_Brown}
                skeleton={nodes.Suit_Head_3.skeleton}
              />
              <skinnedMesh
                name="Suit_Head_4"
                geometry={nodes.Suit_Head_4.geometry}
                material={materials.Brown}
                skeleton={nodes.Suit_Head_4.skeleton}
              />
            </group>
            <skinnedMesh
              name="Suit_Legs"
              geometry={nodes.Suit_Legs.geometry}
              material={materials.Black}
              skeleton={nodes.Suit_Legs.skeleton}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            />
          </group>
        </group>
      </group>
    </RigidBody>
  );
}

useGLTF.preload("/sarah.glb");
