/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { RigidBody } from "@react-three/rapier";
import { useAtom } from "jotai";
import { dialogAtom } from "../../../atoms";

export function Sarah(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/sarah.glb");
  const { actions } = useAnimations(animations, group);
  const [mount, setMount] = React.useState(false);
  const [dialog, setDialog] = useAtom(dialogAtom);
  useEffect(() => {
    // const idle = Object.keys(actions).find((key) => key.includes("Idle"));
    // actions[idle].play();
    setMount(true);
  }, [actions]);
  return !mount ? null : (
    <RigidBody type="fixed" colliders="trimesh">
      <group
        ref={group}
        {...props}
        position={[1, -1, 0]}
        onClick={() => {
          setDialog({
            npc: "sara",
            prompt: `
You are playing the role of Sarah Thompson, a 28-year-old artist and Community Art Coordinator in the town of Meadowbrook. Sarah is creative, compassionate, and highly intuitive. She connects deeply with the townspeople, organizing art exhibitions, workshops, and collaborative projects to enrich the community. Sarah is resourceful, optimistic, and always ready to help others.

When a player interacts with you, respond warmly and engage them in conversations about art, community events, or personal growth. Occasionally, provide the player with random quests that involve assisting with art projects, exploring town mysteries, or fostering community connections. Ensure that your responses are supportive, insightful, and encourage the player to delve deeper into the town's enigmatic phenomena.

### Example Quests:
1. Help Organize the Art Exhibition: Assist Sarah in setting up the upcoming exhibition by gathering materials, arranging displays, and promoting the event.
2. Explore the Abandoned Warehouse: Investigate the old warehouse rumored to be a hidden art studio, searching for clues about past community events.
3. Create a Mural: Collaborate with Sarah to design and paint a community mural that reflects the town's history and spirit.
4. Assist a Young Artist: Mentor a local child who is struggling with their art, providing guidance and encouragement to help them express themselves.
5. Investigate Strange Symbols: Help Sarah decipher mysterious symbols found in her latest artwork, which may be linked to Meadowbrook's hidden secrets.

### Dialogue Formatting Guidelines:
- Character Names: Use uppercase for character names.
- Dialogue: Follow the character name with their spoken lines.
- Actions/Expressions: Include descriptive text in parentheses to convey emotions and movements.

### Constraints:
- Maintain a friendly and slightly mysterious tone.
- Keep the language appropriate for a teen audience.
- Avoid any explicit language or content.
- Ensure that quests are varied and encourage exploration and interaction within the community.
`,
          });
        }}
        dispose={null}
      >
        <group name="Root_Scene">
          <group name="RootNode">
            <group
              name="CharacterArmature"
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <primitive object={nodes.Root} />
            </group>
            <group name="Suit_Body" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <skinnedMesh
                name="Suit_Body_1"
                geometry={nodes.Suit_Body_1.geometry}
                material={materials.Black}
                skeleton={nodes.Suit_Body_1.skeleton}
              />
              <skinnedMesh
                name="Suit_Body_2"
                geometry={nodes.Suit_Body_2.geometry}
                material={materials.White}
                skeleton={nodes.Suit_Body_2.skeleton}
              />
              <skinnedMesh
                name="Suit_Body_3"
                geometry={nodes.Suit_Body_3.geometry}
                material={materials.Skin}
                skeleton={nodes.Suit_Body_3.skeleton}
              />
            </group>
            <group name="Suit_Feet" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <skinnedMesh
                name="Suit_Feet_1"
                geometry={nodes.Suit_Feet_1.geometry}
                material={materials.Black}
                skeleton={nodes.Suit_Feet_1.skeleton}
              />
              <skinnedMesh
                name="Suit_Feet_2"
                geometry={nodes.Suit_Feet_2.geometry}
                material={materials.Skin}
                skeleton={nodes.Suit_Feet_2.skeleton}
              />
            </group>
            <group name="Suit_Head" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <skinnedMesh
                name="Suit_Head_1"
                geometry={nodes.Suit_Head_1.geometry}
                material={materials.Skin}
                skeleton={nodes.Suit_Head_1.skeleton}
              />
              <skinnedMesh
                name="Suit_Head_2"
                geometry={nodes.Suit_Head_2.geometry}
                material={materials.Hair_Blond}
                skeleton={nodes.Suit_Head_2.skeleton}
              />
              <skinnedMesh
                name="Suit_Head_3"
                geometry={nodes.Suit_Head_3.geometry}
                material={materials.Hair_Brown}
                skeleton={nodes.Suit_Head_3.skeleton}
              />
              <skinnedMesh
                name="Suit_Head_4"
                geometry={nodes.Suit_Head_4.geometry}
                material={materials.Brown}
                skeleton={nodes.Suit_Head_4.skeleton}
              />
            </group>
            <skinnedMesh
              name="Suit_Legs"
              geometry={nodes.Suit_Legs.geometry}
              material={materials.Black}
              skeleton={nodes.Suit_Legs.skeleton}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            />
          </group>
        </group>
      </group>
    </RigidBody>
  );
}

useGLTF.preload("/sarah.glb");
