/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Mirror(props) {
  const { nodes, materials } = useGLTF("/Mirror.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mirror.geometry}
        material={materials.Mat}
      />
    </group>
  );
}

useGLTF.preload("/Mirror.glb");
